# Generated by Django 2.2 on 2019-04-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='这个天气所在的国家', max_length=50)),
                ('country', models.CharField(blank=True, help_text='这个天气所在的国家', max_length=50, null=True)),
                ('query_time', models.DateTimeField(auto_now=True, help_text='查询时间', null=True, verbose_name='查询时间')),
                ('latitude', models.FloatField(default=0.0, help_text='纬度', verbose_name='纬度')),
                ('longitude', models.FloatField(default=0.0, help_text='经度', verbose_name='经度')),
                ('weather', models.CharField(blank=True, help_text='天气，比如多云', max_length=100, null=True)),
                ('weather_description', models.CharField(blank=True, help_text='天气的描述', max_length=1000, null=True)),
                ('temperature', models.IntegerField(default=0, help_text='温度，摄氏度')),
                ('max_temperature', models.IntegerField(default=0, help_text='最高温度，摄氏度')),
                ('min_temperature', models.IntegerField(default=0, help_text='最低温度，摄氏度')),
                ('wind_speed', models.FloatField(default=0.0, help_text='风速')),
                ('icon', models.CharField(blank=True, help_text='天气的图标id', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'unique_together': {('name', 'country')},
            },
        ),
    ]
